### PR TITLE
modified get_deals to use property_history flag

### PR DESCRIPTION
**Pull request by seanofahey**
This fix addresses issue #63 using the first of the two potential fix approaches

### CODE REVIEW

**Comment by maelle** [comment]
Thanks @seanofahey!

I would like to add a test for the behaviour but at the moment, with the "demo" key I don't see any difference when I set `property_history` FALSE or TRUE.

@stephlocke I think we should make Boolean parameters logical (e.g. FALSE not "false"), but that's a breaking change.

**Comment by maelle** [comment]
I've just found an example, I'll add a test.

**Comment by stephlocke** [comment]
I made the values "true" and "false" because it:
1. reduces the code requirement to turn the booleans consistently into the format expected by hubspot's API which is case sensitive
2. means that if they add a third value like "latest", the working with strings means no refactoring to support it

As much as TRUE/FALSE is the more R way of doing things normally, I'd prefer to keep things as strings for now.

Thanks for the PR(s) by the way @seanofahey!

**Comment by maelle** [comment]
Ok, I'll revert that and then merge, thanks @stephlocke . Thanks again @seanofahey!

**Comment by seanofahey** [comment]
Happy to help. Thanks for the great project.

**Pull request merged**
